# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_2.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label = QtWidgets.QLabel(self.groupBox_4)
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.marketComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.marketComboBox.setObjectName("marketComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.marketComboBox)
        self.Label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.marketSeriesComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.marketSeriesComboBox.setObjectName("marketSeriesComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.marketSeriesComboBox)
        self.Label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.marketMethodComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.marketMethodComboBox.setObjectName("marketMethodComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.marketMethodComboBox)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.addMarketSeriesButton = QtWidgets.QPushButton(self.groupBox_4)
        self.addMarketSeriesButton.setObjectName("addMarketSeriesButton")
        self.verticalLayout_5.addWidget(self.addMarketSeriesButton)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.classifiedComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.classifiedComboBox.setModelColumn(0)
        self.classifiedComboBox.setObjectName("classifiedComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.classifiedComboBox)
        self.Label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.classifiedSeriesComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.classifiedSeriesComboBox.setObjectName("classifiedSeriesComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.classifiedSeriesComboBox)
        self.Label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.Label_6.setObjectName("Label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.classifiedMethodComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.classifiedMethodComboBox.setObjectName("classifiedMethodComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.classifiedMethodComboBox)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.addClassifiedSeriesButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addClassifiedSeriesButton.setObjectName("addClassifiedSeriesButton")
        self.verticalLayout_6.addWidget(self.addClassifiedSeriesButton)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_7 = QtWidgets.QLabel(self.groupBox)
        self.Label_7.setObjectName("Label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.stockLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockLineEdit.sizePolicy().hasHeightForWidth())
        self.stockLineEdit.setSizePolicy(sizePolicy)
        self.stockLineEdit.setFrame(True)
        self.stockLineEdit.setPlaceholderText("")
        self.stockLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.stockLineEdit.setClearButtonEnabled(True)
        self.stockLineEdit.setObjectName("stockLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stockLineEdit)
        self.Label_8 = QtWidgets.QLabel(self.groupBox)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.stockSeriesComboBox = QtWidgets.QComboBox(self.groupBox)
        self.stockSeriesComboBox.setObjectName("stockSeriesComboBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stockSeriesComboBox)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.addStockSeriesButton = QtWidgets.QPushButton(self.groupBox)
        self.addStockSeriesButton.setObjectName("addStockSeriesButton")
        self.verticalLayout_7.addWidget(self.addStockSeriesButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.Label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.startDateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.startDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2001, 1, 1), QtCore.QTime(0, 0, 0)))
        self.startDateEdit.setObjectName("startDateEdit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startDateEdit)
        self.Label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_15.setObjectName("Label_15")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.endDateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.endDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.endDateEdit.setObjectName("endDateEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endDateEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_7)
        self.verticalLayout.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.serieslistWidget = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serieslistWidget.sizePolicy().hasHeightForWidth())
        self.serieslistWidget.setSizePolicy(sizePolicy)
        self.serieslistWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.serieslistWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.serieslistWidget.setObjectName("serieslistWidget")
        self.verticalLayout_4.addWidget(self.serieslistWidget)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.loadButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_6.addWidget(self.loadButton, 1, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.groupBox_2)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_6.addWidget(self.saveButton, 1, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.groupBox_2)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_6.addWidget(self.clearButton, 0, 1, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_6.addWidget(self.deleteButton, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.generateButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateButton.sizePolicy().hasHeightForWidth())
        self.generateButton.setSizePolicy(sizePolicy)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphWidget = QtWebEngineWidgets.QWebEngineView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setAutoFillBackground(False)
        self.graphWidget.setObjectName("graphWidget")
        self.horizontalLayout.addWidget(self.graphWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setVerticalSpacing(11)
        self.formLayout_4.setObjectName("formLayout_4")
        self.Label_9 = QtWidgets.QLabel(self.tab_2)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.basicDataLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.basicDataLineEdit.setReadOnly(True)
        self.basicDataLineEdit.setObjectName("basicDataLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.basicDataLineEdit)
        self.Label_10 = QtWidgets.QLabel(self.tab_2)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.allStockLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.allStockLineEdit.setReadOnly(True)
        self.allStockLineEdit.setObjectName("allStockLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.allStockLineEdit)
        self.allStockLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allStockLabel.sizePolicy().hasHeightForWidth())
        self.allStockLabel.setSizePolicy(sizePolicy)
        self.allStockLabel.setText("")
        self.allStockLabel.setObjectName("allStockLabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.allStockLabel)
        self.Label_11 = QtWidgets.QLabel(self.tab_2)
        self.Label_11.setObjectName("Label_11")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.stockDataLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.stockDataLineEdit.setReadOnly(True)
        self.stockDataLineEdit.setObjectName("stockDataLineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stockDataLineEdit)
        self.Label_12 = QtWidgets.QLabel(self.tab_2)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.statisticLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.statisticLineEdit.setReadOnly(True)
        self.statisticLineEdit.setObjectName("statisticLineEdit")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.statisticLineEdit)
        self.Label_13 = QtWidgets.QLabel(self.tab_2)
        self.Label_13.setObjectName("Label_13")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.classifiedLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.classifiedLineEdit.setReadOnly(True)
        self.classifiedLineEdit.setObjectName("classifiedLineEdit")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.classifiedLineEdit)
        self.basicDataLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicDataLabel.sizePolicy().hasHeightForWidth())
        self.basicDataLabel.setSizePolicy(sizePolicy)
        self.basicDataLabel.setAutoFillBackground(False)
        self.basicDataLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.basicDataLabel.setObjectName("basicDataLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.basicDataLabel)
        self.stockDataLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockDataLabel.sizePolicy().hasHeightForWidth())
        self.stockDataLabel.setSizePolicy(sizePolicy)
        self.stockDataLabel.setText("")
        self.stockDataLabel.setObjectName("stockDataLabel")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.stockDataLabel)
        self.statisticLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statisticLabel.sizePolicy().hasHeightForWidth())
        self.statisticLabel.setSizePolicy(sizePolicy)
        self.statisticLabel.setText("")
        self.statisticLabel.setObjectName("statisticLabel")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.statisticLabel)
        self.classifiedLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifiedLabel.sizePolicy().hasHeightForWidth())
        self.classifiedLabel.setSizePolicy(sizePolicy)
        self.classifiedLabel.setText("")
        self.classifiedLabel.setObjectName("classifiedLabel")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.classifiedLabel)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_5.addWidget(self.textBrowser)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setVerticalSpacing(30)
        self.formLayout_5.setObjectName("formLayout_5")
        self.checkButton_1 = QtWidgets.QPushButton(self.tab_2)
        self.checkButton_1.setObjectName("checkButton_1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkButton_1)
        self.bulidButton_1 = QtWidgets.QPushButton(self.tab_2)
        self.bulidButton_1.setObjectName("bulidButton_1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bulidButton_1)
        self.checkButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.checkButton_2.setObjectName("checkButton_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkButton_2)
        self.checkButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.checkButton_3.setObjectName("checkButton_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkButton_3)
        self.checkButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.checkButton_4.setObjectName("checkButton_4")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkButton_4)
        self.checkButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.checkButton_5.setObjectName("checkButton_5")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkButton_5)
        self.bulidButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.bulidButton_2.setObjectName("bulidButton_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bulidButton_2)
        self.bulidButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.bulidButton_4.setObjectName("bulidButton_4")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bulidButton_4)
        self.bulidButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.bulidButton_5.setObjectName("bulidButton_5")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bulidButton_5)
        self.bulidButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.bulidButton_3.setObjectName("bulidButton_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bulidButton_3)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.clearButton.clicked.connect(self.serieslistWidget.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据分析"))
        self.groupBox_4.setTitle(_translate("MainWindow", "市场"))
        self.Label.setText(_translate("MainWindow", "市场"))
        self.Label_2.setText(_translate("MainWindow", "指标"))
        self.Label_3.setText(_translate("MainWindow", "统计方式"))
        self.addMarketSeriesButton.setText(_translate("MainWindow", "添加序列"))
        self.groupBox_3.setTitle(_translate("MainWindow", "行业"))
        self.Label_4.setText(_translate("MainWindow", "行业"))
        self.Label_5.setText(_translate("MainWindow", "指标"))
        self.Label_6.setText(_translate("MainWindow", "统计方式"))
        self.addClassifiedSeriesButton.setText(_translate("MainWindow", "添加序列"))
        self.groupBox.setTitle(_translate("MainWindow", "个股"))
        self.Label_7.setText(_translate("MainWindow", "股票代码"))
        self.stockLineEdit.setInputMask(_translate("MainWindow", "000000"))
        self.stockLineEdit.setText(_translate("MainWindow", "600000"))
        self.Label_8.setText(_translate("MainWindow", "指标"))
        self.addStockSeriesButton.setText(_translate("MainWindow", "添加序列"))
        self.groupBox_5.setTitle(_translate("MainWindow", "时间段"))
        self.Label_14.setText(_translate("MainWindow", "开始时间"))
        self.startDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.Label_15.setText(_translate("MainWindow", "结束时间"))
        self.endDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.groupBox_2.setTitle(_translate("MainWindow", "图表序列"))
        self.loadButton.setText(_translate("MainWindow", "加载图表序列"))
        self.saveButton.setText(_translate("MainWindow", "保存图表序列"))
        self.clearButton.setText(_translate("MainWindow", "清空序列"))
        self.deleteButton.setText(_translate("MainWindow", "删除序列"))
        self.generateButton.setText(_translate("MainWindow", "生成统计图表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "图表"))
        self.Label_9.setText(_translate("MainWindow", "基础数据库（交易日快照）"))
        self.Label_10.setText(_translate("MainWindow", "整合数据库"))
        self.Label_11.setText(_translate("MainWindow", "基础数据库（个股快照）"))
        self.Label_12.setText(_translate("MainWindow", "个股统计数据库"))
        self.Label_13.setText(_translate("MainWindow", "行业统计数据库"))
        self.basicDataLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\"></span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "使用说明"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">1.</span><span style=\" text-decoration: underline; color:#000000;\">基础数据库（交易日快照）</span><span style=\" color:#000000;\">是根据目录下</span><span style=\" font-weight:600; color:#000000;\">date_week.txt</span><span style=\" color:#000000;\">的日期列表到数据库进行下载，每天一个快照。每次重建这个数据库，后面四个都要重建。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">2.</span><span style=\" text-decoration: underline; color:#000000;\">整合数据库</span><span style=\" color:#000000;\">是根据</span><span style=\" text-decoration: underline; color:#000000;\">基础数据库（交易日快照）</span><span style=\" color:#000000;\">，全部整合成一个数据文件。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">3.</span><span style=\" text-decoration: underline; color:#000000;\">基础数据库（个股快照）</span><span style=\" color:#000000;\">是根据</span><span style=\" text-decoration: underline; color:#000000;\">整合数据库</span><span style=\" color:#000000;\">，按照个股切割成单独的数据文件。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">4.</span><span style=\" text-decoration: underline; color:#000000;\">个股统计数据库</span><span style=\" color:#000000;\">以及</span><span style=\" text-decoration: underline; color:#000000;\">行业统计数据库</span><span style=\" color:#000000;\">，是根据</span><span style=\" text-decoration: underline; color:#000000;\">基础数据库（个股快照）</span><span style=\" color:#000000;\">建立，可以同时进行重建。</span></p></body></html>"))
        self.checkButton_1.setText(_translate("MainWindow", "检查"))
        self.bulidButton_1.setText(_translate("MainWindow", "重建"))
        self.checkButton_2.setText(_translate("MainWindow", "检查"))
        self.checkButton_3.setText(_translate("MainWindow", "检查"))
        self.checkButton_4.setText(_translate("MainWindow", "检查"))
        self.checkButton_5.setText(_translate("MainWindow", "检查"))
        self.bulidButton_2.setText(_translate("MainWindow", "重建"))
        self.bulidButton_4.setText(_translate("MainWindow", "重建"))
        self.bulidButton_5.setText(_translate("MainWindow", "重建"))
        self.bulidButton_3.setText(_translate("MainWindow", "重建"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "数据"))

from PyQt5 import QtWebEngineWidgets
